version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
    timezone: Europe/Berlin
