# GENERATED CONTENT
# remove repo from adrianjost/.github/synced/workflows/generator.js before editing
queue_rules:
  - name: branchProtection
    conditions:
      - '-merged'
pull_request_rules:
  - name: label PRs with conflicts
    conditions:
      - conflict
    actions:
      label:
        add:
          - has conflicts
  - name: remove has conflicts label if conflicts got resolved
    conditions:
      - label~=has conflicts
      - '-conflict'
    actions:
      label:
        remove:
          - has conflicts
  - name: let @adrianjost recreate dependabot PRs with conflicts
    conditions:
      - author~=dependabot(-preview)?\[bot\]
      - conflict
    actions:
      comment:
        message: Someone with write access should tell dependabot to recreate this PR.
  - name: auto merge passing Dependabot pull requests
    conditions:
      - author~=dependabot(-preview)?\[bot\]
    actions:
      queue:
        name: branchProtection
        method: squash
  - name: auto merge when ready to merge label is set
    conditions:
      - label=ready to merge
    actions:
      queue:
        name: branchProtection
        method: merge
  - name: remove ready to merge when merged
    conditions:
      - merged
      - label=ready to merge
    actions:
      label:
        remove:
          - ready to merge
  - name: delete merged branches
    conditions:
      - merged
      - label!=WIP
    actions:
      delete_head_branch: {}
