name: Files Sync Action
author: Adrian Jost
branding:
  color: green
  icon: copy
description: Copies files from the action's environment (or any other repo) to many other repos.
inputs:
  COMMIT_MESSAGE:
    description: |
      The commit message that will be used to commit the changed files. Check the README for all interpolation options.
    required: false
  DRY_RUN:
    description: |
      Run everything except for the copying, removing and commiting functionality.
    required: false
  FILE_PATTERNS:
    description: |
      New line deliminated regex expressions to select files from the source repository. All filpaths start with the repos fullname without a leading slash. The delimiter between path segments is a forward slash.
    required: true
  GITHUB_TOKEN:
    description: Token to use to get repos and write secrets
    required: true
  GIT_EMAIL:
    description: |
      The e-mail address used to commit the synced files. Defaults to $GITHUB_ACTOR@users.noreply.github.com
    required: false
  GIT_USERNAME:
    description: |
      The username used to commit the synced files. Defaults to $GITHUB_ACTOR
    required: false
  SKIP_DELETE:
    description: |
      Will omit all delete operations for matching files present in `TARGET_REPO` but not existant in `SRC_REPO` if set to `true`. Defaults to `false`.
    required: false
  SKIP_CLEANUP:
    description: |
      If set to true or 1, the cleanup step to remove the temporary workding directory at the end will be skipped. Usefull for debugging purposes.
    required: false
  SRC_REPO:
    description: |
      Repo from where files should be synced from. Defaults to $GITHUB_REPOSITORY.
    required: false
  TARGET_REPOS:
    description: |
      New line deliminated list of repositories where the files should be synced to. The given access token must have access to all listed repositories.
    required: true
  TMPDIR:
    description: |
      The working directory where all sync operations will be done. Defaults to `tmp-${Date.now().toString()}`
    required: false
  SRC_ROOT:
    description: |
      Prepends this to all filepaths in the source repository. Defaults to `/`.
    required: false
  TARGET_ROOT:
    description: |
      Prepends this to all filepaths in the target repository. Defaults to `/`.
    required: false
runs:
  main: dist/index.js
  using: node12
